directory: ~/music
plugins: scrub convert fetchart embedart lastgenre lyrics info mbsync
per_disc_numbering: yes
import:
  move: yes
  languages: en
paths:
  albumtype:soundtrack: Soundtrack/$album/$disc-$track $title
  comp: Compilation/$album/$disc-$track $title
  singleton: Singleton/$artist/$title
  default: $albumartist/$album/$disc-$track $title
convert:
  auto: yes
