#!/usr/bin/env bash
set -o errexit
set -o nounset
# set -o xtrace
set -o pipefail

cd "$(dirname $BASH_SOURCE)"

ln -sf "$PWD/.xprofile" "$HOME"
ln -sf "$PWD/.Xresources" "$HOME"
dmesg | grep -q 'X1 Carbon 2nd' && ln -sf "$PWD/.Xmodmap-X1C" "$HOME/.Xmodmap"
lsusb | grep -q 'HHKB' && ln -sf "$PWD/.Xmodmap-HHKB" "$HOME/.Xmodmap"

ln -sf "$PWD/.makepkg.conf" "$HOME"

ln -sf "$PWD/.tmux.conf" "$HOME"
ln -sf "$PWD/.zshrc" "$HOME"

mkdir -p "$HOME/.config/nvim/autoload"
curl -sfLo "$HOME/.config/nvim/autoload/plug.vim" 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

ln -sf "$PWD/.vimperatorrc" "$HOME"

for profile in $(cat "$HOME/.mozilla/firefox/profiles.ini" | grep 'Path' | cut -b6-)
do
	chrome="$HOME/.mozilla/firefox/$profile/chrome"
	mkdir -p "$chrome"
	ln -sf "$PWD/userChrome.css" "$chrome"
	ln -sf "$PWD/userContent.css" "$chrome"
done

mkdir -p "$HOME/.config" && ln -sf "$PWD/user-dirs.dirs" "$HOME/.config"
mkdir -p "$HOME/.config/i3" && ln -sf "$PWD/i3" "$HOME/.config/i3/config"
mkdir -p "$HOME/.config/i3status" && ln -sf "$PWD/i3status" "$HOME/.config/i3status/config"
mkdir -p "$HOME/.config/mpv" && ln -sf "$PWD/mpv-input.conf" "$HOME/.config/mpv/input.conf"
mkdir -p "$HOME/.config/mpv" && ln -sf "$PWD/mpv.conf" "$HOME/.config/mpv/mpv.conf"
mkdir -p "$HOME/.config/transmission-cli" && ln -sf "$PWD/transmission-settings.json" "$HOME/.config/transmission-cli/settings.json"
mkdir -p "$HOME/.config/zathura" && ln -sf "$PWD/zathurarc" "$HOME/.config/zathura"
mkdir -p "$HOME/.config/nvim" && ln -sf "$PWD/init.vim" "$HOME/.config/nvim"

mkdir -p "$HOME/.gnupg" && ln -sf "$PWD/gpg-agent.conf" "$HOME/.gnupg/gpg-agent.conf"
ln -sf "$PWD/.pam_environment" "$HOME"

mkdir -p "$HOME/.local/share/applications" && ln -sf "$PWD/chromium.desktop" "$HOME/.local/share/applications"

ln -sf "$PWD/.gitconfig" "$HOME"
mkdir -p "$HOME/.config/git" && ln -sf "$PWD/gitignore" "$HOME/.config/git/ignore"

rm -rf "$HOME/.gem"
sudo gem update --system
gem install --conservative gem-ctags
gem update
gem install --conservative puma -v 2.16.0 -- --with-opt-include=/usr/include/openssl-1.0
gem install --conservative bundler gemstash git-up rails ronn travis
bundle config mirror.https://rubygems.org http://localhost:9292

cp -f "$PWD/.npmrc" "$HOME/.npmrc"
npm install -g npm yarn

pip install --user pylast requests
ln -sf "$PWD/beets-config.yaml" "$(beet config -p)"

mkdir -p "$HOME/bin"
for bin in $(ls "$PWD/bin")
do
	ln -sf "$PWD/bin/$bin" "$HOME/bin"
done

for folder in $(find "$HOME/.insync" -maxdepth 1 -type d \( ! -name '.*' \))
do
	if [[ ! -e "$folder" ]]
	then
		ln -s "$folder" "$HOME"
	fi
done
