#!/usr/bin/env bash
set -o errexit
set -o nounset
# set -o xtrace
set -o pipefail

cd "$(dirname $BASH_SOURCE)"

# ln -sf "$PWD/.makepkg.conf" "$HOME"

mkdir -p "$HOME/.config/"
ln -sf "$PWD/alacritty" "$HOME/.config"
ln -sf "$PWD/aria2" "$HOME/.config"
ln -sf "$PWD/mpd" "$HOME/.config"
ln -sf "$PWD/ncmpcpp" "$HOME/.config"
ln -sf "$PWD/beets" "$HOME/.config"
ln -sf "$PWD/mpv" "$HOME/.config"
ln -sf "$PWD/sway" "$HOME/.config"
ln -sf "$PWD/mako" "$HOME/.config"
ln -sf "$PWD/tridactyl" "$HOME/.config"
ln -sf "$PWD/wofi" "$HOME/.config"
ln -sf "$PWD/fontconfig" "$HOME/.config"
ln -sf "$PWD/git" "$HOME/.config"
ln -sf "$PWD/bottom" "$HOME/.config"
ln -sf "$PWD/btop" "$HOME/.config"
ln -sf "$PWD/.tmux.conf" "$HOME"
ln -sf "$PWD/.zshrc" "$HOME"

mkdir -p "$HOME/.local/share"
ln -sf "$PWD/applications" "$HOME/.local/share"

mkdir -p "$HOME/.local/share/mpd/playlists"
mkdir -p "$HOME/.local/state/mpd"
touch "$HOME/.local/state/mpd/database"

mkdir -p "$HOME/.local/state/beets"

mkdir -p "$HOME/.local/state/ncmpcpp"

mkdir -p "$HOME/.config/nvim/autoload"
curl -sfLo "$HOME/.config/nvim/autoload/plug.vim" 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
mkdir -p "$HOME/.config/nvim" && ln -sf "$PWD/init.vim" "$HOME/.config/nvim"

for PROFILE in $(cat "$HOME/.mozilla/firefox/profiles.ini" | grep 'Path' | cut -b6-)
do
	PROFILE_DIR="$HOME/.mozilla/firefox/$PROFILE"
	CHROME_DIR="$PROFILE_DIR/chrome"
	mkdir -p "$CHROME_DIR"
	ln -sf "$PWD/firefox/userChrome.css" "$CHROME_DIR"
	ln -sf "$PWD/firefox/user.js" "$PROFILE_DIR"
done

ln -sf "$PWD/user-dirs.dirs" "$HOME/.config"
# mkdir -p "$HOME/.config/zathura" && ln -sf "$PWD/zathurarc" "$HOME/.config/zathura"

mkdir -p "$HOME/.gnupg" && ln -sf "$PWD/gpg-agent.conf" "$HOME/.gnupg/gpg-agent.conf"
ln -sf "$PWD/.pam_environment" "$HOME"

# yarn global add typescript

# mkdir -p "$HOME/.certbot"

ln -sfn "$PWD/bin" "$HOME"

# for folder in $(find "$HOME/.insync/my-drive" -maxdepth 1 -type d \( ! -name '.*' \))
# do
# 	if [[ ! -e "$folder" ]]
# 	then
# 		ln -s "$folder" "$HOME"
# 	fi
# done
