" Available Mappings
" Normal <C-g> <C-j> <C-l>
" Insert <C-b> <C-h> <C-j> <C-l> <C-m>

set rtp+=~/.vim/bundle/vundle
call vundle#rc()
Plugin 'gmarik/vundle'

Plugin 'chrisbra/SudoEdit.vim'

Plugin 'tpope/vim-dispatch'
Plugin 'Shougo/vimproc.vim'

Plugin 'altercation/vim-colors-solarized'
colorscheme solarized
set background=light
let g:solarized_termtrans=1

Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-speeddating'
Plugin 'tpope/vim-unimpaired'
Plugin 'godlygeek/tabular'
nmap <Leader>a :Tabularize 
vmap <Leader>a :Tabularize 
Plugin 'AndrewRadev/splitjoin.vim'
nmap <Leader>j :SplitjoinJoin<CR>
nmap <Leader>s :SplitjoinSplit<CR>
Plugin 'bronson/vim-visual-star-search'

Plugin 'kana/vim-textobj-user'
Plugin 'kana/vim-textobj-entire'
Plugin 'kana/vim-textobj-lastpat'
Plugin 'kana/vim-textobj-syntax'

Plugin 'tpope/vim-surround'
let g:surround_no_insert_mappings=1
Plugin 'jiangmiao/auto-pairs'
Plugin 'tpope/vim-endwise'

Plugin 'Valloric/YouCompleteMe'
let g:ycm_collect_identifiers_from_tags_files=0
let g:ycm_key_list_select_completion=[]
let g:ycm_key_invoke_completion=''
let g:ycm_key_detailed_diagnostics=''

Plugin 'SirVer/ultisnips'
let g:UltiSnipsExpandTrigger='<Tab>'
let g:UltiSnipsJumpForwardTrigger='<Tab>'
let g:UltiSnipsJumpBackwardTrigger='<S-Tab>'

Plugin 'Shougo/unite.vim'
let g:unite_cursor_line_highlight='CursorLine'
call unite#custom#source('file_rec/async', 'ignore_pattern', '/\.gem/\|/\.git/\|/tmp/')
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])
function! s:uniteSettings()
  setlocal completeopt=
  imap <buffer> <Tab> <C-x><C-f><C-x><C-y>
endfunction
autocmd FileType unite call s:uniteSettings()
nnoremap <C-n>f :Unite -no-split -start-insert file_rec/async file/new<CR>
nnoremap <C-n><C-f> :Unite -no-split -start-insert file_rec/async file/new<CR>

Plugin 'mileszs/ack.vim'
nnoremap <C-n>s :Ack 
nnoremap <C-n><C-s> :Ack 

Plugin 'tpope/vim-fugitive'
nnoremap <C-k> :Gstatus<CR>
Plugin 'gregsexton/gitv'

Plugin 'mbbill/undotree'
set undofile
set undodir=$HOME/.vimundo
let g:undotree_SplitWidth=32
nnoremap <C-h> :UndotreeToggle<CR>

Plugin 'bling/vim-airline'
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_detect_whitespace=0
set noshowmode
let g:airline_theme='solarized'

Plugin 'szw/vim-tags'
let g:vim_tags_directories=[]

Plugin 'scrooloose/syntastic'
let g:syntastic_check_on_open=1
let g:syntastic_enable_signs=0
let g:syntastic_always_populate_loc_list=1
let g:syntastic_auto_loc_list=1
let g:syntastic_quiet_messages={'level': 'warnings'}
let g:syntastic_ruby_checkers=['rubocop']

Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-lua-ftplugin'
let g:lua_complete_dynamic = 0
let g:lua_check_syntax = 0
let g:lua_check_globals = 0
Plugin 'tpope/vim-haml'
Plugin 'chrisbra/color_highlight'
let g:colorizer_auto_filetype = 'css,scss,sass,html,haml'
Plugin 'jelera/vim-javascript-syntax'
Plugin 'marijnh/tern_for_vim'
Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-rake'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-markdown'

Plugin 'tpope/vim-sensible'
set foldmethod=syntax
set nowrap
set number
set nobackup
set noswapfile
set hidden

set expandtab tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType python setlocal et ts=4 sw=4 sts=4
autocmd FileType sh setlocal noet ts=4 sw=4 sts=4

nmap <C-m> :Make<CR>
autocmd FileType ruby nmap <buffer> <C-m> :Rrunner<CR>
