set rtp+=~/.vim/bundle/vundle
call vundle#rc()
Bundle 'gmarik/vundle'

Bundle 'chrisbra/SudoEdit.vim'

Bundle 'tpope/vim-dispatch'
Bundle 'Shougo/vimproc.vim'

Bundle 'altercation/vim-colors-solarized'
colorscheme solarized
set background=light
let g:solarized_termtrans=1

Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-commentary'
Bundle 'tpope/vim-speeddating'
Bundle 'tpope/vim-unimpaired'
Bundle 'godlygeek/tabular'
nmap <Leader>a :Tabularize 
vmap <Leader>a :Tabularize 
Bundle 'AndrewRadev/splitjoin.vim'
nmap <Leader>j :SplitjoinJoin<CR>
nmap <Leader>s :SplitjoinSplit<CR>
Bundle 'bronson/vim-visual-star-search'

Bundle 'kana/vim-textobj-user'
Bundle 'kana/vim-textobj-entire'
Bundle 'kana/vim-textobj-lastpat'
Bundle 'kana/vim-textobj-syntax'

Bundle 'tpope/vim-surround'
let g:surround_no_insert_mappings=1
Bundle 'jiangmiao/auto-pairs'
Bundle 'tpope/vim-endwise'

Bundle 'Valloric/YouCompleteMe'
let g:ycm_collect_identifiers_from_tags_files=0 " disabled for high ram usage
let g:ycm_key_list_select_completion=[]
let g:ycm_key_invoke_completion=''
let g:ycm_key_detailed_diagnostics=''

Bundle 'SirVer/ultisnips'
let g:UltiSnipsExpandTrigger='<Tab>'
let g:UltiSnipsJumpForwardTrigger='<Tab>'
let g:UltiSnipsJumpBackwardTrigger='<S-Tab>'

Bundle 'Shougo/unite.vim'
let g:unite_cursor_line_highlight='CursorLine'
call unite#custom#source('file_rec/async', 'ignore_pattern', '/\.gem/\|/\.git/\|/tmp/')
call unite#filters#matcher_default#use(['matcher_fuzzy'])
call unite#filters#sorter_default#use(['sorter_rank'])
function! s:unite_my_settings()
  setlocal completeopt=
  imap <buffer> <Tab> <C-x><C-f><C-x><C-y>
endfunction
autocmd FileType unite call s:unite_my_settings()
nnoremap <C-p> :Unite -no-split -start-insert file_rec/async file/new<CR>

Bundle 'mileszs/ack.vim'
nnoremap <C-l> :Ack 

Bundle 'tpope/vim-fugitive'
nnoremap <C-k> :Gstatus<CR>

Bundle 'mbbill/undotree'
set undofile
set undodir=$HOME/.vimundo
let g:undotree_SplitWidth=32
nnoremap <C-h> :UndotreeToggle<CR>

Bundle 'bling/vim-airline'
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline_detect_whitespace=0
set noshowmode
let g:airline_theme='solarized'

Bundle 'szw/vim-tags'
let g:vim_tags_directories=[]
Bundle 'scrooloose/syntastic'
let g:syntastic_check_on_open = 1
let g:syntastic_enable_signs = 0
let g:syntastic_enable_balloons = 0
let g:syntastic_auto_loc_list = 1
let g:syntastic_mode_map = {
  \ 'mode': 'active',
  \ 'passive_filetypes': []
\}

Bundle 'tpope/vim-bundler'
Bundle 'chrisbra/color_highlight'
let g:colorizer_auto_filetype = 'css,scss,sass,html,haml'
Bundle 'tpope/vim-haml'
Bundle 'xolox/vim-misc'
Bundle 'xolox/vim-lua-ftplugin'
let g:lua_complete_dynamic = 0
let g:lua_check_syntax = 0
let g:lua_check_globals = 0
Bundle 'tpope/vim-markdown'
Bundle 'tpope/vim-rake'
Bundle 'tpope/vim-rails'
Bundle 'marijnh/tern_for_vim'

Bundle 'tpope/vim-sensible'

set foldmethod=syntax
set nowrap
set number
set nobackup
set noswapfile
set hidden

set expandtab tabstop=2 shiftwidth=2 softtabstop=2
autocmd FileType python setlocal et ts=4 sw=4 sts=4
