directory: ~/music
statefile: ~/.local/state/beets/state.pickle
library: ~/.local/state/beets/library.db
plugins: scrub fetchart lyrics info mbsync mbsubmit ftintitle
per_disc_numbering: yes
import:
  move: yes
  languages: en
paths:
  albumtype:soundtrack: Soundtrack/$album/$disc-$track $title
  comp: Compilation/$album/$disc-$track $title
  singleton: Singleton/$artist/$title
  default: $albumartist/$album/$disc-$track $title
fetchart:
  high_resolution: true
