#!/bin/sh

if [[ -d /etc/X11/xinit/xinitrc.d ]]
then
  for file in /etc/X11/xinit/xinitrc.d/*
  do
    [ -x "$file" ] && source "$file"
  done
  unset file
fi

xrdb -merge ~/.Xresources
xmodmap ~/.Xmodmap

dex -a -e Awesome
exec awesome
