autoload -Uz compinit && compinit
zstyle ':completion:*' completer _expand _complete _ignored _match _correct _approximate _prefix
zstyle ':completion:*' completions 1
zstyle ':completion:*' condition 1
zstyle ':completion:*' glob 1
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' matcher-list '+' '+m:{[:lower:]}={[:upper:]}' '+m:{[:lower:][:upper:]}={[:upper:][:lower:]}' '+r:|[._-]=** r:|=** l:|=*'
zstyle ':completion:*' match-original both
zstyle ':completion:*' max-errors 3
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' substitute 1
zstyle ':compinstall' filename "$HOME/.zshrc"
setopt appendhistory extendedglob correctall

autoload -U colors && colors
autoload -Uz vcs_info && precmd() { vcs_info }
zstyle ':vcs_info:*' enable git hg svn
zstyle ':vcs_info:git*' formats "%r:%b"
status_line() {
  local ssh=${(%):-%n@%m:%~}
  local git=" $vcs_info_msg_0_"

  local ssh_length=${#ssh}
  local git_length=${#git}

  echo "${(r.(($COLUMNS - $git_length)).)ssh}$git"
}
setopt prompt_subst
PROMPT='<< %?
%{$bg[white]%}$(status_line)%{$reset_color%}
>> '

chpwd() {
  local ruby_project_directory="$(find_ancestor_directory_containing Gemfile)"
  if [ -n "$ruby_project_directory" ]
  then
    local ruby_engine=$(echo 'puts defined?(RUBY_ENGINE) ? RUBY_ENGINE : "ruby"' | ruby)
    local ruby_version=$(echo 'puts RUBY_VERSION' | ruby)
    local gem_path=$(echo 'puts Gem.path.join(":")' | ruby)
    export GEM_HOME="$ruby_project_directory/.gem/$ruby_engine/$ruby_version"
    export GEM_PATH="$GEM_HOME:$gem_path"
  else
    unset GEM_HOME
    unset GEM_PATH
  fi
}
find_ancestor_directory_containing() {
  local slashes=${PWD//[^\/]/}
  local directory="$PWD"
  for (( n=${#slashes}; n>0; --n ))
  do
    if test -e "$directory/$1"
    then
      echo "$directory"
      return
    fi
    directory="$directory/.."
  done
}
chpwd

HISTFILE="$HOME/.histfile"
HISTSIZE=10000
SAVEHIST=10000
setopt hist_expire_dups_first hist_ignore_dups share_history

bindkey -v

export EDITOR='vim'
export PAGER='less -R'
export PATH="$HOME/.gem/ruby/2.0.0/bin:$HOME/.cabal/bin:$HOME/.local/bin:$PATH"

setopt long_list_jobs

alias chgrp='chgrp --preserve-root'
alias chmod='chmod --preserve-root'
alias chown='chown --preserve-root'
alias cp='cp -i'
alias diff='colordiff -u'
alias df='df -h'
alias du='du -c -h'
alias grep='grep --color=auto'
alias ln='ln -i'
alias mkdir='mkdir -p -v'
alias mv='mv -i'
alias nano='nano -w'
alias ping='ping -c 5'
alias rm='rm -i'

alias ls='ls -hF --color=auto'
alias lsa='ls -a'
alias lsl='ls -l'
alias lsal='ls -al'
alias lsla='ls -al'

setopt auto_pushd pushd_ignore_dups

alias pacup='yaourt -Syua'
alias pacin='yaourt -Sy'
alias pacun='yaourt -Rcns'
alias pacls='yaourt -Q'
alias pacse='yaourt -Ss'
pacds() {
  tmp=${TMPDIR-/tmp}/pacman-disowned-$UID-$$
  db=$tmp/db
  fs=$tmp/fs

  mkdir "$tmp"

  pacman -Qlq | sort -u > "$db"

  find /bin /etc /lib /sbin /usr \
    ! -name lost+found \
    \( -type d -printf '%p/\n' -o -print \) | sort > "$fs"

  comm -23 "$fs" "$db"

  rm -rf "$tmp"
}
alias pacmd='pacman -Qii | grep "^MODIFIED" | sed "s/MODIFIED\s\+//" | sort'

eval "$(hub alias -s)"
current_branch() { echo ${$(git symbolic-ref HEAD 2> /dev/null)#refs/heads/} }
alias gitst='hub status -sb'
alias gitlg='hub log --color --graph --abbrev-commit --pretty=format:"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset"'
alias gitdf='hub diff --color=always'
alias gitpp='hub up && git push'
alias gitmf='hub merge --ff-only'
alias gitcm='hub commit'
alias gitap='hub add --patch'
alias gitrs='hub reset'
alias gitbr='hub branch'
alias gitco='hub checkout'
alias gitcr='hub create'
gitcl() {
  git clone --recursive $@ || exit
  if [[ ${*[-1]##*.} -eq git ]]
  then
    pushd ${${*[-1]##*/}%*.git} 1>/dev/null
  else
    pushd $*[-1] 1>/dev/null
  fi
  for branch in $(git branch -r | grep -v HEAD)
  do
    git branch --track ${branch##*/} $branch 2>/dev/null
  done
  popd 1>/dev/null
}

local gpg_env_file="$HOME/.gnupg/gpg-agent.env"
if pgrep -u $USER gpg-agent &>/dev/null
then
  eval $(cat $gpg_env_file)
  eval $(cut -d= -f1 $gpg_env_file | xargs echo export)
else
  eval $(gpg-agent --daemon --enable-ssh-support --write-env-file $gpg_env_file 2>/dev/null)
  chmod 600 $gpg_env_file
fi
export GPG_TTY="$(tty)"
